version: '3.9'
services:
  pptx-speech-dev:
    build:
      context: ./src/pptx-speech
      dockerfile: Dockerfile_dev

    container_name: pptx-speech-dev
    # restart: unless-stopped
    volumes:
      - './src/pptx-speech:/workspace/pptx-speech'
      - './vsc_extensions/pptx-speech:/root/.vscode-server/extensions'
    # ports:
    #   - '8080:8080'
    stdin_open: true
    tty: true