version: '3.9'
services:
  pptx-speech-dev:
    build:
      # context: ./src/flow_pdf
      dockerfile: Dockerfile_dev

    container_name: pptx-speech-dev
    # restart: unless-stopped
    volumes:
      - './:/workspace/pptx-speech'
      - './vsc_extensions:/root/.vscode-server/extensions'
    # ports:
    #   - '8080:8080'
    stdin_open: true
    tty: true