# FROM 117503445/dev-python
FROM ubuntu:20.04

WORKDIR /workspace/pptx-speech

ENV DEBIAN_FRONTEND=nonintercative

# COPY ./script/init.sh /script/init.sh
# RUN /script/init.sh

# https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/quickstarts/setup-platform?
RUN apt-get update && apt-get install -y build-essential libssl-dev ca-certificates libasound2 wget

RUN apt-get install -y software-properties-common

RUN add-apt-repository ppa:deadsnakes/ppa && apt-get install -y python3.11

RUN echo "alias python='python3.11'" >> ~/.bashrc
RUN echo "export PATH="/root/.local/bin:$PATH"" >> ~/.bashrc
RUN apt-get install -y curl
RUN curl -sSL https://install.python-poetry.org | python3.11 -
RUN /root/.local/bin/poetry config virtualenvs.in-project true
RUN /root/.local/bin/poetry env use python3.11

SHELL [ "/bin/bash" ]